deviceSettings:
    id: f560704a-e8a3-4e92-ac2f-c1c49b263a2c
    type: Pulse

connectionSettings:
    serverHost: "http://localhost:8080"
    requestInterval: 60
    connTimeout: 20
    maxIdleConns: 10
    idleConnTimeout: 30
    disableCompression: true

userID: e90d4d9d-d0f0-43f5-a6d5-67b9c93fc0f4
